# Длина строки.
line-length = 99
# Список директорий, которые не проверяются.
exclude = ["alembic", "__init__.py"]

[lint]
# Список кодов правил или префиксов, которые необходимо включить в проверку.
select = ["E", "F", "I"]

[format]
# Использовать одинарные кавычки.
quote-style = "single"
# Не переносить строки с "магическими запятыми", даже если они не будут превышать длину строки.
skip-magic-trailing-comma = false

[lint.isort]
# Объединяет все импорты из одного места в одну строку.
combine-as-imports = true
# Список модулей, которые следует рассматривать как сторонние.
known-first-party = ["src"]
