version: '3.9'

services:
  db_test:
    image: postgres:14
    container_name: test_postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      retries: 10
      timeout: 5s
    restart: unless-stopped

volumes:
  pg_data_test:
