version: '3.3'

volumes:

  pg_data:

services:

  db:
    container_name: data-base
    image: postgres:13.10
    env_file: .env
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 12
    ports:
      - "${PORT_BD_POSTGRES}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data