version: '3.8'

services:
  db:
    container_name: postgres_local
    image: postgres:17.2-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_local
    image: dpage/pgadmin4:8.14
    restart: always
    env_file:
      - ../.env
    ports:
      - "5600:80"
    depends_on:
      - db

volumes:
  postgres_data:
