services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 5s
    restart: always

  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: ${PWD}/
      dockerfile: infra/stage/stage.Dockerfile
      args:
        APP_PORT=: ${APP_PORT}
        APP_VERSION: ${APP_VERSION}
        PYTHON_VERSION: ${PYTHON_VERSION}
        POETRY_VERSION: ${POETRY_VERSION}
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - PATH="/app/.venv/bin:$PATH"
      - UVICORN_RELOAD=true
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db
    volumes:
      - ${PWD}/${MEDIA_FOLDER}:/app/media
      - ${PWD}/src:/app/src
      - ${PWD}/alembic:/app/alembic
    profiles:
      - app_dc
    restart: always

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    env_file:
      - ${PWD}/.env
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ${PWD}/pgadmin/config_local.py:/pgadmin4/config_local.py
      - ${PWD}/pgadmin/create-admin-folder.sh:/create-admin-folder.sh
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgadmin4/.pgpass
    entrypoint: ["/bin/sh", "/create-admin-folder.sh"]
    profiles:
      - app_dc
      - pgadmin
    restart: always

configs:
  servers.json:
    content: |
      {
        "Servers": {
          "${PGADMIN_SERVER_ID_TABIT}": {
            "Name": "${PGADMIN_SERVER_NAME_TABIT}",
            "Group": "${PGADMIN_SERVER_GROUP_TABIT}",
            "Host": "${DB_CONTAINER_NAME}",
            "Port": ${DB_PORT},
            "SSLMode": "${SSL_MODE}",
            "MaintenanceDB": "${POSTGRES_DB}",
            "Username": "${POSTGRES_USER}",
            "PassFile": "/.pgpass"
          }
        }
      }
  pgpass:
    content: |
        ${DB_CONTAINER_NAME}:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}

volumes:
  postgres_data:
    driver: local
    name: ${DB_VOLUME_NAME}
  pgadmin_data:
    driver: local
    name: ${PGADMIN_VOLUME_NAME}
