services:
  db:
    container_name: ${DB_CONTAINER_NAME:-postgres_local}
    image: postgres:${POSTGRES_VERSION:-17.2-alpine}
    restart: always
    env_file:
      - ${PWD}/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

  app:
    container_name: ${APP_CONTAINER_NAME:-tabit}
    build:
      context: ${PWD}/
      dockerfile: infra/stage/stage.Dockerfile
    restart: always
    ports:
      - ${APP_PORT:-8000}:8000
    depends_on:
      - db
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/${MEDIA_FOLDER}:/app/media
    profiles:
      - app_dc
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - PATH="/app/.venv/bin:$PATH"
      - DB_HOST=${DB_CONTAINER_NAME:-postgres_local}
      - DB_PORT=5432

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin_local}
    image: dpage/pgadmin4:${PGADMIN_VERSION:-8.14}
    restart: always
    env_file:
      - ${PWD}/.env
    ports:
      - ${PGADMIN_PORT:-5600}:80
    depends_on:
      - db
    profiles:
      - app_dc
      - pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ${PWD}/pgadmin/config_local.py:/pgadmin4/config_local.py
      - ${PWD}/pgadmin/create-admin-folder.sh:/create-admin-folder.sh
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgadmin4/.pgpass
    entrypoint: ["/bin/sh", "/create-admin-folder.sh"]


configs:
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Tabit Database",
            "Group": "Tabit Server Group",
            "Port": 5432,
            "Host": "${DB_CONTAINER_NAME:-postgres_local}",
            "SSLMode": "prefer",
            "MaintenanceDB": "${POSTGRES_DB:-tabit}",
            "Username": "${POSTGRES_USER:-warlock}",
          }
        }
      }
  pgpass:
    content: |
      postgres_local:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  pgadmin_data:
