services:
  db:
    container_name: postgres_tabit_local
    image: postgres:17.2-alpine
    restart: always
    env_file:
      - ./../../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: tabit
    build:
      context: ../..
      dockerfile: infra/stage/stage.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./../../.env
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - PATH="/app/.venv/bin:$PATH"

  pgadmin:
    container_name: pgadmin_local
    image: dpage/pgadmin4:8.14
    restart: always
    env_file:
      - ./../../.env
    ports:
      - "5600:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - /home/${{ secrets.USERNAME }}/tabit/pgadmin/servers.json:/pgadmin4/servers.json
      - /home/${{ secrets.USERNAME }}/tabit/pgadmin/config_local.py:/pgadmin4/config_local.py
      - /home/${{ secrets.USERNAME }}/tabit/pgadmin/.pgpass:/pgadmin4/.pgpass
      - /home/${{ secrets.USERNAME }}/tabit/pgadmin/create-admin-folder.sh:/create-admin-folder.sh
    entrypoint: ["/bin/sh", "/create-admin-folder.sh"]

volumes:
  postgres_data:
  pgadmin_data:
