"""changed_pk_constraint_for_meetingresult

Revision ID: 03
Revises: 02
Create Date: 2025-04-24 12:48:45.471238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meetingresult_pkey', 'meetingresult', type_='primary')
    op.create_primary_key('meetingresult_pkey', 'meetingresult', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meetingresult_pkey', 'meetingresult', type_='primary')
    op.create_primary_key('meetingresult_pkey', 'meetingresult', ['id', 'meeting_id'])
    # ### end Alembic commands ###
