"""Delete id in association models

Revision ID: 03
Revises: 02
Create Date: 2025-03-23 21:34:12.476105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('associationusercomment_id_key', 'associationusercomment', type_='unique')
    op.drop_constraint('associationusercomment_left_id_fkey', 'associationusercomment', type_='foreignkey')
    op.drop_constraint('associationusercomment_right_id_fkey', 'associationusercomment', type_='foreignkey')
    op.create_foreign_key(None, 'associationusercomment', 'commentfeed', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'associationusercomment', 'usertabit', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_column('associationusercomment', 'id')
    op.drop_constraint('associationusermeeting_id_key', 'associationusermeeting', type_='unique')
    op.drop_constraint('associationusermeeting_right_id_fkey', 'associationusermeeting', type_='foreignkey')
    op.drop_constraint('associationusermeeting_left_id_fkey', 'associationusermeeting', type_='foreignkey')
    op.create_foreign_key(None, 'associationusermeeting', 'meeting', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'associationusermeeting', 'usertabit', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_column('associationusermeeting', 'id')
    op.drop_constraint('associationuserproblem_right_id_fkey', 'associationuserproblem', type_='foreignkey')
    op.drop_constraint('associationuserproblem_left_id_fkey', 'associationuserproblem', type_='foreignkey')
    op.create_foreign_key(None, 'associationuserproblem', 'problem', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'associationuserproblem', 'usertabit', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('associationusertags_id_key', 'associationusertags', type_='unique')
    op.drop_constraint('associationusertags_left_id_fkey', 'associationusertags', type_='foreignkey')
    op.drop_constraint('associationusertags_right_id_fkey', 'associationusertags', type_='foreignkey')
    op.create_foreign_key(None, 'associationusertags', 'taguser', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'associationusertags', 'usertabit', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_column('associationusertags', 'id')
    op.drop_constraint('associationusertask_id_key', 'associationusertask', type_='unique')
    op.drop_column('associationusertask', 'id')
    op.add_column('problem', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_constraint('problem_company_slug_fkey', 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'company', ['company_id'], ['id'])
    op.drop_column('problem', 'company_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('company_slug', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key('problem_company_slug_fkey', 'problem', 'company', ['company_slug'], ['slug'])
    op.drop_column('problem', 'company_id')
    op.add_column('associationusertask', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('associationusertask_id_key', 'associationusertask', ['id'])
    op.add_column('associationusertags', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'associationusertags', type_='foreignkey')
    op.drop_constraint(None, 'associationusertags', type_='foreignkey')
    op.create_foreign_key('associationusertags_right_id_fkey', 'associationusertags', 'taguser', ['right_id'], ['id'])
    op.create_foreign_key('associationusertags_left_id_fkey', 'associationusertags', 'usertabit', ['left_id'], ['id'])
    op.create_unique_constraint('associationusertags_id_key', 'associationusertags', ['id'])
    op.drop_constraint(None, 'associationuserproblem', type_='foreignkey')
    op.drop_constraint(None, 'associationuserproblem', type_='foreignkey')
    op.create_foreign_key('associationuserproblem_left_id_fkey', 'associationuserproblem', 'usertabit', ['left_id'], ['id'])
    op.create_foreign_key('associationuserproblem_right_id_fkey', 'associationuserproblem', 'problem', ['right_id'], ['id'])
    op.add_column('associationusermeeting', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'associationusermeeting', type_='foreignkey')
    op.drop_constraint(None, 'associationusermeeting', type_='foreignkey')
    op.create_foreign_key('associationusermeeting_left_id_fkey', 'associationusermeeting', 'usertabit', ['left_id'], ['id'])
    op.create_foreign_key('associationusermeeting_right_id_fkey', 'associationusermeeting', 'meeting', ['right_id'], ['id'])
    op.create_unique_constraint('associationusermeeting_id_key', 'associationusermeeting', ['id'])
    op.add_column('associationusercomment', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'associationusercomment', type_='foreignkey')
    op.drop_constraint(None, 'associationusercomment', type_='foreignkey')
    op.create_foreign_key('associationusercomment_right_id_fkey', 'associationusercomment', 'commentfeed', ['right_id'], ['id'])
    op.create_foreign_key('associationusercomment_left_id_fkey', 'associationusercomment', 'usertabit', ['left_id'], ['id'])
    op.create_unique_constraint('associationusercomment_id_key', 'associationusercomment', ['id'])
    # ### end Alembic commands ###
