"""fix department

Revision ID: 03
Revises: 02
Create Date: 2025-03-21 13:29:24.534355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    op.alter_column('meeting', 'place',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problem', 'company_slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    op.create_unique_constraint(None, 'problem', ['company_slug'])
    op.drop_constraint('usertabit_current_department_id_fkey', 'usertabit', type_='foreignkey')
    op.drop_constraint('usertabit_previous_department_id_fkey', 'usertabit', type_='foreignkey')
    op.create_foreign_key(None, 'usertabit', 'department', ['previous_department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usertabit', 'department', ['current_department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertabit', type_='foreignkey')
    op.drop_constraint(None, 'usertabit', type_='foreignkey')
    op.create_foreign_key('usertabit_previous_department_id_fkey', 'usertabit', 'department', ['previous_department_id'], ['id'])
    op.create_foreign_key('usertabit_current_department_id_fkey', 'usertabit', 'department', ['current_department_id'], ['id'])
    op.drop_constraint(None, 'problem', type_='unique')
    op.alter_column('problem', 'company_slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('meeting', 'place',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('company', 'slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
