"""survey

Revision ID: 03
Revises: 02
Create Date: 2025-07-09 12:11:53.474715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveycycleforcompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELED', 'POSTPONED', name='surveysstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('surveycycleforuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('survey_cycle_for_company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELED', 'POSTPONED', name='surveysstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_company_id'], ['surveycycleforcompany.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('luschercolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.Integer(), nullable=False),
    sa.Column('selection_1', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_2', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_3', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_4', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_5', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_6', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_7', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_8', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('company', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=260),
               existing_nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=260),
               existing_nullable=False)
    op.alter_column('usertag', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('votingfeed', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_unique_constraint('unique_name_message_id', 'votingfeed', ['name', 'message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_message_id', 'votingfeed', type_='unique')
    op.alter_column('votingfeed', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('usertag', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('company', 'slug',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_table('luschercolor')
    op.drop_table('surveycycleforuser')
    op.drop_table('surveycycleforcompany')
    # ### end Alembic commands ###
