"""surveys

Revision ID: 03
Revises: 02
Create Date: 2025-05-02 16:22:02.423371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveyschedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_slug', sa.String(length=110), nullable=False),
    sa.Column('survey_tag', sa.Enum('EMO', 'TEST', name='surveystags'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELED', 'POSTPONED', name='surveysstatus'), nullable=False),
    sa.Column('cycles_dates', sa.JSON(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveydata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=110), nullable=False),
    sa.Column('cycle_date', sa.Date(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shedule_id'], ['surveyschedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('company', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('company', 'slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_table('surveydata')
    op.drop_table('surveyschedule')
    # ### end Alembic commands ###

    # Удаление типов ENUM
    op.execute('DROP TYPE IF EXISTS surveysstatus')
    op.execute('DROP TYPE IF EXISTS surveystags')
