"""surveys

Revision ID: 03
Revises: 02
Create Date: 2025-04-19 22:16:45.771626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveylist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.Enum('emo', 'test', name='surveystags'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyschedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_slug', sa.String(length=25), nullable=False),
    sa.Column('survey_tag', sa.Enum('emo', 'test', name='surveystags'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'complited', 'canceled', 'postponed', name='surveysstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyschedulecycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('survey_schedule_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_schedule_id'], ['surveyschedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveydata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_shedule_id', sa.Integer(), nullable=False),
    sa.Column('survey_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=25), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['surveyschedulecycle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_list_id'], ['surveylist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_shedule_id'], ['surveyschedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveydata')
    op.drop_table('surveyschedulecycle')
    op.drop_table('surveyschedule')
    op.drop_table('surveylist')
    # ### end Alembic commands ###
