"""slug_gt_2553

Revision ID: 03
Revises: 02
Create Date: 2025-04-21 15:05:48.544406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=260),
               existing_nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=260),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'slug',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('company', 'slug',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
