"""surveys

Revision ID: 03
Revises: 02
Create Date: 2025-04-29 15:25:59.299280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveylist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.Enum('EMO', 'TEST', name='surveystags'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyschedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_slug', sa.String(length=110), nullable=False),
    sa.Column('survey_tag', sa.Enum('EMO', 'TEST', name='surveystags'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELED', 'POSTPONED', name='surveysstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyschedulecycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('survey_schedule_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_schedule_id'], ['surveyschedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveydata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_shedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=110), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['company.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['surveyschedulecycle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_shedule_id'], ['surveyschedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyanswer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_data_id', sa.Integer(), nullable=False),
    sa.Column('survey_list_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_data_id'], ['surveydata.id'], ),
    sa.ForeignKeyConstraint(['survey_list_id'], ['surveylist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('company', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    op.alter_column('department', 'slug',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=110),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('company', 'slug',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_table('surveyanswer')
    op.drop_table('surveydata')
    op.drop_table('surveyschedulecycle')
    op.drop_table('surveyschedule')
    op.drop_table('surveylist')
    # ### end Alembic commands ###
