"""add rating to comment and user/comment association model

Revision ID: 04
Revises: 03
Create Date: 2025-02-20 18:07:18.577077

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04'
down_revision: Union[str, None] = '03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associationusercomment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('left_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['usertabit.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['commentfeed.id'], ),
    sa.PrimaryKeyConstraint('id', 'left_id', 'right_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('left_id', 'right_id')
    )
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('commentfeed', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_table('associationusercomment')
    op.drop_column('commentfeed', 'rating')
    # ### end Alembic commands ###
