"""fix slug length

Revision ID: 04_fix_slug_length
Revises: 03_survey
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04'
down_revision = '03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'company', 'slug',
        existing_type=sa.String(length=25),
        type_=sa.String(length=260),
        existing_nullable=False
    )
    op.alter_column(
        'department', 'slug',
        existing_type=sa.String(length=25),
        type_=sa.String(length=260),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'department', 'slug',
        existing_type=sa.String(length=260),
        type_=sa.String(length=25),
        existing_nullable=False
    )
    op.alter_column(
        'company', 'slug',
        existing_type=sa.String(length=260),
        type_=sa.String(length=25),
        existing_nullable=False
    )
    # ### end Alembic commands ###
