"""luscher_2

Revision ID: 04
Revises: 03
Create Date: 2025-07-16 13:18:37.357540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04'
down_revision: Union[str, None] = '03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('luschercolor')
    op.execute("DROP TYPE IF EXISTS luscherscolorenum")
    op.create_table('luschercolorfirst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.Integer(), nullable=False),
    sa.Column('selection_1', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_2', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_3', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_4', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_5', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_6', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_7', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_8', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('luschercolorsecond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.Integer(), nullable=False),
    sa.Column('selection_1', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_2', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_3', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_4', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_5', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_6', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_7', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_8', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.create_unique_constraint(None, 'surveycycleforcompany', ['id'])
    op.create_unique_constraint(None, 'surveycycleforuser', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveycycleforuser', type_='unique')
    op.drop_constraint(None, 'surveycycleforcompany', type_='unique')
    op.create_table('luschercolor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selection_1', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_2', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_3', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_4', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_5', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_6', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_7', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_8', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], name='luschercolor_survey_cycle_for_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='luschercolor_pkey')
    )
    op.drop_table('luschercolorsecond')
    op.drop_table('luschercolorfirst')
    op.execute("""
        CREATE TYPE luscherscolorenum AS ENUM 
        ('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey')
    """)
    # ### end Alembic commands ###
