"""Create research tables

Revision ID: 04_research
Revises: 03_survey
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04_research'
down_revision = '03_survey'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['companyuser.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_researchtype_id'), 'researchtype', ['id'], unique=False)

    op.create_table('researchinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('В работе', 'Завершен', 'Отменен', 'Отложен', name='surveysstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_type_id'], ['researchtype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_researchinstance_id'), 'researchinstance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_researchinstance_id'), table_name='researchinstance')
    op.drop_table('researchinstance')
    op.drop_index(op.f('ix_researchtype_id'), table_name='researchtype')
    op.drop_table('researchtype')
    # ### end Alembic commands ###
