"""research

Revision ID: 04
Revises: 03
Create Date: 2025-08-28 20:33:40.816502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04'
down_revision: Union[str, None] = '03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sociometriccriterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('choice_type', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='choicetype'), nullable=False),
    sa.Column('max_choices', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('TACTICAL_LEADERSHIP', 'STRATEGIC_LEADERSHIP', name='sociometriccategoryenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('communication_type', sa.Enum('HIGH', 'MIDDLE', 'LOW', name='communicationtype'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('leadership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('leadership_type', sa.Enum('TACTICAL_LEADERSHIP', 'STRATEGIC_LEADERSHIP', name='sociometriccategoryenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('researchtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['companyuser.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('riskgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('risk_group_type', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', name='riskgrouptype'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('luschercolorfirst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.Integer(), nullable=False),
    sa.Column('selection_1', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_2', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_3', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_4', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_5', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_6', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_7', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_8', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('luschercolorsecond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.Integer(), nullable=False),
    sa.Column('selection_1', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_2', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_3', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_4', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_5', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_6', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_7', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('selection_8', sa.Enum('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('researchinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELED', 'POSTPONED', name='surveysstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_type_id'], ['researchtype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sociometricchoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('chosen_employee_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('cycle_user_id', sa.Integer(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=True),
    sa.Column('choice_type', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='choicetype'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chosen_employee_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_id'], ['sociometriccriterion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['companyuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sociometricstrategypreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_user_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_user_id'], ['surveycycleforuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('luschercolor')
    op.create_unique_constraint(None, 'surveycycleforcompany', ['id'])
    op.create_unique_constraint(None, 'surveycycleforuser', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveycycleforuser', type_='unique')
    op.drop_constraint(None, 'surveycycleforcompany', type_='unique')
    op.create_table('luschercolor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_cycle_for_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selection_1', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_2', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_3', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_4', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_5', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_6', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_7', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('selection_8', postgresql.ENUM('Blue', 'Green', 'Red', 'Yellow', 'Violet', 'Brown', 'Black', 'Grey', name='luscherscolorenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_cycle_for_user_id'], ['surveycycleforuser.id'], name='luschercolor_survey_cycle_for_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='luschercolor_pkey')
    )
    op.drop_table('sociometricstrategypreference')
    op.drop_table('sociometricchoice')
    op.drop_table('researchinstance')
    op.drop_table('luschercolorsecond')
    op.drop_table('luschercolorfirst')
    op.drop_table('riskgroup')
    op.drop_table('researchtype')
    op.drop_table('leadership')
    op.drop_table('communication')
    op.drop_table('sociometriccriterion')
    # ### end Alembic commands ###
