"""add transfer_counter to Task model

Revision ID: 05
Revises: 04
Create Date: 2025-02-26 22:14:55.983179

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06'
down_revision: Union[str, None] = '04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associationusercomment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('left_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column(
        'created_at', postgresql.TIMESTAMP(
            timezone=True
        ), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column(
        'updated_at', postgresql.TIMESTAMP(
            timezone=True
        ), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['left_id'], ['usertabit.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['commentfeed.id'], ),
    sa.PrimaryKeyConstraint('id', 'left_id', 'right_id'),
    sa.UniqueConstraint('id')
    )
    op.drop_constraint(
        'associationusertask_left_id_right_id_key', 'associationusertask', type_='unique'
    )
    op.add_column('commentfeed', sa.Column('rating', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'licensetype', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licensetype', type_='unique')
    op.drop_column('commentfeed', 'rating')
    op.create_unique_constraint(
        'associationusertask_left_id_right_id_key', 'associationusertask', ['left_id', 'right_id']
    )
    op.drop_table('associationusercomment')
    # ### end Alembic commands ###
