"""remove id field from multi primary key models

Revision ID: 06
Revises: 05
Create Date: 2025-03-01 15:49:10.757607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06'
down_revision: Union[str, None] = '05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('associationusercomment_id_key', 'associationusercomment', type_='unique')
    op.drop_constraint('associationusercomment_left_id_right_id_key', 'associationusercomment', type_='unique')
    op.drop_column('associationusercomment', 'id')
    op.drop_constraint('associationusermeeting_id_key', 'associationusermeeting', type_='unique')
    op.drop_column('associationusermeeting', 'id')
    op.drop_constraint('associationuserproblem_id_key', 'associationuserproblem', type_='unique')
    op.drop_column('associationuserproblem', 'id')
    op.drop_constraint('associationusertags_id_key', 'associationusertags', type_='unique')
    op.drop_column('associationusertags', 'id')
    op.drop_constraint('associationusertask_id_key', 'associationusertask', type_='unique')
    op.drop_column('associationusertask', 'id')
    op.drop_constraint('resultmeeting_id_key', 'resultmeeting', type_='unique')
    op.drop_column('resultmeeting', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultmeeting', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('resultmeeting_id_key', 'resultmeeting', ['id'])
    op.add_column('associationusertask', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('associationusertask_id_key', 'associationusertask', ['id'])
    op.add_column('associationusertags', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('associationusertags_id_key', 'associationusertags', ['id'])
    op.add_column('associationuserproblem', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint('associationuserproblem_id_key', 'associationuserproblem', ['id'])
    op.add_column('associationusermeeting', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint('associationusermeeting_id_key', 'associationusermeeting', ['id'])
    op.add_column('associationusercomment', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint('associationusercomment_left_id_right_id_key', 'associationusercomment', ['left_id', 'right_id'])
    op.create_unique_constraint('associationusercomment_id_key', 'associationusercomment', ['id'])
    # ### end Alembic commands ###
