"""доб. каскадное уд. в моделе UserTabit и Task для связи с AssociationUserTask

Revision ID: 21d88f9b4050
Revises: 2daa78b6eba1
Create Date: 2025-02-25 21:07:33.288923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d88f9b4050'
down_revision: Union[str, None] = '2daa78b6eba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'associationusertask_right_id_fkey', 'associationusertask', type_='foreignkey'
    )
    op.drop_constraint(
        'associationusertask_left_id_fkey', 'associationusertask', type_='foreignkey'
    )
# Создаём новые внешние ключи с каскадным удалением
    op.create_foreign_key(
        'associationusertask_right_id_fkey',
        'associationusertask',
        'task',
        ['right_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'associationusertask_left_id_fkey',
        'associationusertask',
        'usertabit',
        ['left_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'associationusertask_right_id_fkey', 'associationusertask', type_='foreignkey'
    )
    op.drop_constraint(
        'associationusertask_left_id_fkey', 'associationusertask', type_='foreignkey'
    )

    op.create_foreign_key(
        'associationusertask_right_id_fkey',
        'associationusertask',
        'task',
        ['right_id'],
        ['id']
    )
    op.create_foreign_key(
        'associationusertask_left_id_fkey',
        'associationusertask',
        'usertabit',
        ['left_id'],
        ['id']
    )
    # ### end Alembic commands ###
