"""add cascading del for problem_id Task model

Revision ID: 24b5659ab0cd
Revises: b7e4c238d0ed
Create Date: 2025-02-22 21:10:43.514866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b5659ab0cd'
down_revision: Union[str, None] = 'b7e4c238d0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task', ['id'])
    op.drop_constraint('task_problem_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_problem_id_fkey', 'task', 'problem', ['problem_id'], ['id'])
    op.drop_constraint(None, 'task', type_='unique')
    # ### end Alembic commands ###
