"""удалены primary_key поля left и right id модели AssociationUserTask

Revision ID: 2daa78b6eba1
Revises: 24b5659ab0cd
Create Date: 2025-02-23 01:19:24.883214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daa78b6eba1'
down_revision: Union[str, None] = '24b5659ab0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'associationusertask', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'associationusertask', type_='unique')
    # ### end Alembic commands ###
