"""First migration

Revision ID: 4a28cf67d85e
Revises:
Create Date: 2025-01-21 00:22:39.631419

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '4a28cf67d85e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
