"""Вернули id в Task с autoincrement

Revision ID: dae11c5cc7c1
Revises: 8a85d4084215
Create Date: 2025-02-20 00:39:07.041406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae11c5cc7c1'
down_revision: Union[str, None] = '111ccacdc7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
