"""initial migration

Revision ID: e452ab207bc8
Revises: 08
Create Date: 2025-01-30 13:04:31.601200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e452ab207bc8'
down_revision: Union[str, None] = '08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'landingpage', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landingpage', type_='unique')
    # ### end Alembic commands ###
