TITLE_NAME_USER: str = 'Имя пользователя сервиса'
TITLE_SURNAME_USER: str = 'Фамилия пользователя сервиса'
TITLE_PATRONYMIC_USER: str = 'Отчество пользователя сервиса'
TITLE_PHONE_NUMBER_USER: str = 'Контактный телефон пользователя сервиса'
TITLE_IS_ACTIVE_USER: str = 'Активен ли пользователь'
TITLE_BIRTHDAY_USER: str = 'День рождение пользователя'
TITLE_TELEGRAM_USERNAME_USER: str = 'Имя пользователя в Telegram'
TITLE_ROLE_USER: str = 'Роль пользователя компании.'
TITLE_START_DATE_EMPLOYMENT_USER: str = 'Дата начало работы сотрудника в компании'
TITLE_END_DATE_EMPLOYMENT_USER: str = 'Дата конца работы сотрудника в компании'
TITLE_AVATAR_LINK_USER: str = 'Ссылка на аватар пользователя'
TITLE_COMPANY_ID_USER: str = 'id компании, в которой работает пользователь'
TITLE_CURRENT_DEPARTMENT_ID_USER: str = 'id отдела, в котором работает пользователь'
TITLE_LAST_DEPARTMENT_ID_USER: str = 'id отдела, в котором работал пользователь до этого'
TITLE_DEPARTMENT_TRANSITION_DATE_USER: str = 'Последняя дата перехода из одного отдела в другой'
TITLE_EMPLOYEE_POSITION_USER: str = 'Позиция в коллективе, указывается админом компании'
TITLE_CREATED_AT_USER: str = 'Дата создания профиля пользователя'
TITLE_UPDATED_AT_USER: str = 'Дата обновления профиля пользователя'


TITLE_NAME_TAG: str = 'Имя тэга'
TITLE_COMPANY_ID_TAG: str = 'id компании, в которой используется тэг'
