services:
  db:
    container_name: postgres_local
    image: postgres:17.2-alpine
    restart: always
    env_file:
      - /home/dev_deploy/infra/stage/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: tabit
    build:
      context: .
      dockerfile: stage.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - /home/dev_deploy/infra/stage/.env
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - PATH="/app/.venv/bin:$PATH"

volumes:
  postgres_data:
