name: Build and push Docker image

on:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      USERNAME:
        required: true
      ENV_FILE:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        shell: bash

      - name: Load variables to GitHub env
        run: |
          grep -v '^#' .env | while read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: view variables (DELETE)
        run: |
          echo "Содержимое файла с секретами: ${{ secrets.ENV_FILE }}"
          echo "Содеримое сформированного файла .env из секретов:"
          if [ -f ".env" ]; then
            cat ".env"
          else
            echo ".env файл не найден."
          fi

          echo "Содержимое переменных окружения GitHub:"
          printenv

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: $IMAGE_REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          logout: false

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          pull: true
          context: .
          file: infra/stage/stage.Dockerfile
          build-args: |
            APP_PORT=${{ env.APP_PORT }}
            APP_VERSION=${{ env.APP_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            POETRY_VERSION=${{ env.POETRY_VERSION }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}:latest
          cache-to: type=inline
