name: Build and push Docker image

on:
  push:
    branches:
      - dev
      - feature/cicd-setup

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} | toLower

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image for Stage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/stage/stage.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save Docker image as tar
        run: docker save -o image.tar ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Upload image tar to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
