name: Ruff Tabit workflow
on: pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check required secrets
      run: |
        if [ -z "${{ secrets.ENV_FILE }}" ]; then
          echo "::error::Secret ENV_FILE is not set!"
          exit 1
        fi

    - name: Extract Python version
      id: extract_py_ver
      run: |
        VERSION=$(echo "${{ secrets.ENV_FILE }}" | grep '^PYTHON_VERSION=' | cut -d'=' -f2)
        if [ -z "$VERSION" ]; then
          echo "::error::PYTHON_VERSION not found in ENV_FILE from secrets!"
          exit 1
        fi
        echo "PYTHON_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ env.PYTHON_VERSION }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff
      run: ruff check --output-format=github .
