name: Deploy to Stage

on:
  push:
    branches:
      - dev
      - feature/cicd-setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image for Stage
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/feature/cicd-setup'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/stage/stage.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_lower }}:latest
            ghcr.io/${{ github.repository_lower }}:${{ github.sha }}

      - name: Stopping old containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if systemctl list-units --full -all | grep -q "tabit.service"; then
              STATUS="$(systemctl is-active tabit.service)"
              if [ "${STATUS}" = "active" ]; then
                sudo systemctl stop tabit.service
                echo "Stopping old containers"
              else
                echo "No active containers"
              fi
            else
              echo "Service tabit.service does not exist, skipping stop"
            fi

      - name: Copy infra via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "infra/"
          target: "${{ env.DEPLOY_PATH }}/infra"
          rm: true
          strip_components: 1

      - name: Configure environment variables on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            touch .env
            if [[ -z "${{ secrets.ENV_FILE }}" ]]; then
              echo "Error: ENV_FILE is not set!"
              exit 1
            fi
            echo "${{ secrets.ENV_FILE }}" > .env

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}/infra/stage/
            sudo systemctl daemon-reload
            sudo systemctl restart tabit.service
            docker-compose -f infra/stage/docker-compose.stage.yaml down
            docker-compose -f infra/stage/docker-compose.stage.yaml pull
            docker-compose -f infra/stage/docker-compose.stage.yaml up -d --force-recreate

      - name: Delete unnecessary files (after deploy)
        run: |
          rm -r infra/stage
          rm -r infra/dev
