name: Deploy to Stage

on:
  push:
    branches:
      - dev
      - feature/cicd-setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy repository to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH }}/app

      - name: Create .env file
        run: |
          ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
          cd ${{ secrets.DEPLOY_PATH }}/app && 
          touch .env && 
          echo "${{ secrets.ENV_FILE }}" > .env
          "

      - name: Build and push Docker image
        run: |
          ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking-no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
          cd ${{ secrets.DEPLOY_PATH }}/app &&
          docker build -t tabit:latest -f infra/stage/stage.Dockerfile .
          "

      - name: Run Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking-no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
          cd ${{ secrets.DEPLOY_PATH }}/app/infra/stage &&
          docker compose -f docker-compose.stage.yaml up -d
          "

      - name: Wait for tabit service to start
        run: |
          ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking-no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl status tabit.service || true"
          until ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking-no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl is-active --quiet tabit.service"; do
            echo "Waiting for tabit.service to be active..."
            sleep 5
          done
          echo "tabit service is active"

      - name: Apply Alembic migrations
        run: |
          ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking-no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "docker exec tabit alembic -c /app/alembic.ini upgrade head"
