name: Deploy to Stage

on:
  push:
    branches:
      - dev
      - feature/cicd-setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev_deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image for Stage
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/feature/cicd-setup'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/stage/Dockerfile
          push: true
          tags: ${{ github.sha }}
      
      - name: Delete unnecessary files
        run: |
          rm -r infra/stage
          rm -r infra/dev

      - name: Stopping old containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            STATUS="$(systemctl is-active tabit.service)"
            if [ "${STATUS}" = "active" ]; then
              sudo systemctl stop tabit.service
              echo "Stopping old containers"
            else
              echo "No active containers"
            fi

      - name: Copy infra via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "infra/"
          target: "${{ env.DEPLOY_PATH }}/infra"
          rm: true
          strip_components: 1

      - name: Execute commands on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            touch .env

            echo "${{ secrets.ENV_FILE }}" > .env

            cd infra/stage/
            docker system prune --force

            sudo cp -f /home/dev_deploy/app/infra/stage/tabit.service /etc/systemd/system/tabit.service
