name: Deploy to Stage

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_and_push.yaml
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      ENV_FILE: ${{ secrets.ENV_FILE }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check secrets
        env:
          HOST: ${{ secrets.HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          REQUIRED_SECRETS=("HOST" "SERVER_USERNAME" "GHCR_PAT" "SSH_PRIVATE_KEY" "ENV_FILE")
          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${!secret}" ]; then
              echo "::error::Missing $secret"
              exit 1
            fi
          done

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        shell: bash

      - name: Load variables to GitHub env
        run: |
          grep -v '^#' .env | while read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Stop old containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if systemctl list-units --full -all | grep -q "tabit.service"; then
              sudo systemctl stop tabit.service || true
            fi
            docker compose -f /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/docker-compose.stage.yaml down || true

      - name: Clean infra folder before copying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            find /home/${{ secrets.SERVER_USERNAME }}/tabit -mindepth 1 -maxdepth 1 ! -name ".ssh" -exec rm -rf {} +
            mkdir -p /home/${{ secrets.SERVER_USERNAME }}/tabit

      - name: Copy infra via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "infra/"
          target: "/home/${{ secrets.SERVER_USERNAME }}/tabit/"
          rm: false

      - name: Copy pgadmin via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "pgadmin/"
          target: "/home/${{ secrets.SERVER_USERNAME }}/tabit/"
          rm: false

      - name: Copy config via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "config/"
          target: "/home/${{ secrets.SERVER_USERNAME }}/tabit/"
          rm: false

      - name: Deploy systemd service file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo cp /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/tabit.service /etc/systemd/system/tabit.service
            sudo systemctl daemon-reload
            sudo systemctl enable tabit.service

      - name: Configure environment variables on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/
            echo "${{ secrets.ENV_FILE }}" > .env

      - name: Pull latest Docker image from GHCR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Создаем временный каталог
            mkdir -p /home/${{ secrets.SERVER_USERNAME }}/tabit/tmp

            # Скачиваем образ и сохраняем его в .tar
            docker pull ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}:latest
            docker save -o /home/${{ secrets.SERVER_USERNAME }}/tabit/tmp/tabit.tar ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}:latest

      - name: Load Docker image on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /home/${{ secrets.SERVER_USERNAME }}/tabit/tmp/tabit.tar
            docker tag ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}:latest ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}:${{ github.sha }}

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/
            sudo systemctl restart tabit.service
            docker compose -f docker-compose.stage.yaml up -d --force-recreate

      - name: Run database migrations inside container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker exec ${{ env.APP_CONTAINER_NAME }} poetry run alembic upgrade head

      - name: Remove old Docker images (keep last 5)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Получаем список всех образов для проекта, сортируем по дате и удаляем все, кроме последних 5
            docker images --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" | grep "${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_PATH }}" | sort -r | tail -n +6 | awk '{print $1}' | xargs -r docker rmi || true
