name: Deploy to Stage

on:
  push:
    branches:
      - dev
      - feature/cicd-setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          cd ${{ env.DEPLOY_PATH }}
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Docker prune and deploy
        run: |
          cd infra/stage/
          docker system prune --force
          sudo docker compose -f infra/stage/docker-compose.stage.yaml up -d

      - name: Wait for tabit service to start
        run: |
          sudo systemctl is-active --quiet tabit.service
          until [ $? -eq 0 ]; do
            echo "Waiting for tabit.service to be active..."
            sleep 5
            sudo systemctl is-active --quiet tabit.service
          done
          echo "tabit service is active"

      - name: Apply Alembic migrations
        run: |
          docker exec tabit alembic -c /app/alembic.ini upgrade head
