name: Deploy to Stage

on:
  push:
    branches:
      - dev
      - feature/cicd-setup

jobs:
  deploy:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/feature/cicd-setup'
    name: Deploy changes on server
    needs: [build_and_push]
    runs-on: ubuntu-latest
    environment:
      name: dev_deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete unnecessary files
        run: |
          rm -r infra/stage
          rm -r infra/dev

      - name: Stopping old containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            STATUS="$(systemctl is-active tabit.service)"
            if [ "${STATUS}" = "active" ]; then
              sudo systemctl stop tabit.service
              echo "Stopping old containers"
              sudo systemctl start tabit.service  # Запускаем сервис после остановки
            else
              echo "No active containers"
            fi

      - name: Copy infra via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "infra/"
          target: "${{ env.DEPLOY_PATH }}/infra"
          rm: true
          strip_components: 1

      - name: Execute commands on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            touch .env

            echo "${{ secrets.ENV_FILE }}" > .env

            cd infra/stage/
            docker system prune --force

            sudo cp -f /home/dev_deploy/app/infra/stage/tabit.service /etc/systemd/system/tabit.service
            sudo systemctl daemon-reload
            sudo systemctl start tabit.service

            sudo systemctl is-active --quiet tabit.service
            until [ $? -eq 0 ]; do
              echo "Waiting for tabit.service to be active..."
              sleep 5
              sudo systemctl is-active --quiet tabit.service
            done

            echo "tabit.service is active"

            docker ps -q -f name=tabit || docker start tabit
            docker exec tabit alembic upgrade head
